# Generated by Django 3.2.7 on 2021-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_commercial_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='award_winning',
            field=models.BooleanField(default=False),
        ),
    ]
