workers = 2
worker_class = "sync"
accesslog = "-"
timeout = 300
bind = "0.0.0.0:8000"
keepalive = 5
worker_tmp_dir = "/dev/shm"
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(l)s "%(T)s"'
max_requests = 1024
